### PR TITLE
Miniproject 1 Solution

### PR DESCRIPTION
**Pull request by avikaitha**

### CODE REVIEW

**Comment by ragavvenkatesan** [comment]
So you are basically changing the regressor file that was provided in the question itself right ?

**Comment by avikaitha** [comment]
Yeah... It's the same file.

**Comment by ragavvenkatesan** [comment]
If you are adding a new file, regressor.py I am not sure if the test_script will work. I like the idea of adding a new file and not changing the 'sample_submission' file. Can you do that and comment out the part of the code in the test_script that reads from sample_submission and have it read from a file that you wrote ? 

This way, the original question will still be preserved as it is and your solution will be added as a new file to the codebase. While you comment out the sample_submission code in the test_script you make a note that it is your solution and add your license to the code as well. 

-R

**Comment by avikaitha** [comment]
Do you want me to upload the test_script as well?

**Comment by ragavvenkatesan** [comment]
Ok, I made a new commit to the miniproject 1 solution. Check that and submit your code accordingly. Make sure you have your license on your code. 
-R

**Comment by avikaitha** [comment]
I have deleted regressor.py and added best_solution.py with MIT License.

**Comment by ragavvenkatesan** [comment]
Ok, I'll merge this.

**Pull request merged**
